language: java
sudo: required
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - ghostscript
  postgresql: "9.6"
services:
  - postgresql
  - docker
before_install:
  - docker-compose -f fedora-test.yml up -d
  - curl -fSL "https://github.com/proarc/proarc/releases/download/v3.2/proarc-3.2-release.zip" -o proarc.zip
  - unzip proarc.zip
  - unzip proarc-3.2-20161121223439/proarc.war
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/jai_core-1.1.1_01.jar -DgroupId=javax.media -DartifactId=jai_core -Dversion=1.1.1_01 -Dpackaging=jar
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/jai_codec-1.3.1_03.jar  -DgroupId=com.sun.media.jai.codec -DartifactId=jai_codec -Dversion=1.3.1_03 -Dpackaging=jar
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/jai_imageio-1.1.jar  -DgroupId=com.sun.media -DartifactId=jai_imageio -Dversion=1.1 -Dpackaging=jar
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/javadjvu-0.8.09.jar  -DgroupId=com.foxtrottechnologies -DartifactId=javadjvu -Dversion=0.8.09 -Dpackaging=jar
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/djvuframe-0.8.09.jar  -DgroupId=com.foxtrottechnologies -DartifactId=djvuframe -Dversion=0.8.09 -Dpackaging=jar
  - mvn -B install:install-file -Dfile=./WEB-INF/lib/org.moxieapps.gwt.uploader-1.1.0.jar -DgroupId=org.moxieapps.gwt -DartifactId=org.moxieapps.gwt.uploader -Dversion=1.1.0 -Dpackaging=jar
  - mvn -B com.isomorphic:isc-maven-plugin:1.1.1:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=6.0p -DbuildDate=2017-12-08
before_script:
  - psql -c 'create database proarc_test;' -U postgres
  - export TZ=Europe/Prague
script:
  - mvn test -Dtest=\!RemoteStorageTest#testDatastreamPurge+testDatastreamEditorWriteReference_External+testIngestPage+testDatastreamEditorRewriteControlGroup+testDatastreamEditorRewriteControlGroup,\!Kramerius4ExportTest#testEmptyOcrExport -pl proarc-common